Translate docs/templating
greyli/flask-docs-zh pull request #122
Opened 2023-08-22 14:43 UTC by lrsgzs

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。
- [x] 如果你是第一个翻译者，同时更新 `.po` 文件顶部的 `FIRST AUTHOR <EMAIL@ADDRESS>`，替换为你的名字和 Email 地址。

2023-08-23 14:32 UTC, greyli requested changes
Thanks for working on this.

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +msgstr "除非配置，Jinja2 被 Flask 配置为以下内容"
customized 翻译为「被自定义」是不是更好一些？

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"``.htm``，``.xml`` 和 ``.xhtml`` 被配置了自动转义。"
少译了「 all templates ending 」

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"所有字符串都被配置了自动转义。"
```suggestion
"所有字符串都会被自动转义。"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"Flask 在 Jinja2 上下文中添加了几个全局函数和助手，此外还有默认值。"
```suggestion
"除了默认值之外，Flask 还在 Jinja2 上下文中插入了一些全局函数和辅助函数。"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"当前请求对象（:class:`flask.request`）。如果模板在没有激活请求上下文的情况下呈现，"
rendered 应翻译为「被渲染」而不是「呈现」，下面三处亦同

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"示在导入模板的上下文中。这部分是由于性能方面的考虑，部分是为了保持事情的明确性。"
```suggestion
"这些变量被添加到变量的上下文中，它们不是全局变量。不同之处在于，默认情况下，这些不会出现"
"在导入模板的上下文中。这样做一部分是由于性能方面的考虑，另一部分是为了保持显式。"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +msgstr "导入宏“带上下文”."
```suggestion
msgstr "导入宏并“携带上下文”."
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +msgstr "使用上下文导入如下所示："
```suggestion
msgstr "像下面这样导入上下文："
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +msgstr "控制自动转义"
```suggestion
msgstr "自动转义控制"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"自动转义是为您自动转义特殊字符的概念。HTML（或 XML，以及 XHTML）意义上的特殊字符是 ``&``，"
```suggestion
"自动转义是指为你自动转义特殊字符。HTML（或 XML，以及 XHTML）意义上的特殊字符是 ``&``，"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"但是，有时您需要在模板中禁用自动转义。如果您想将 HTML 显式地注入页面，例如，如果它们"
保持一致用「你」

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"在使用装饰器的情况下，如果您想使用函数名作为过滤器的名称，那么参数是可选的。注册后，您"
```suggestion
"在使用装饰器的情况下，如果您想使用函数名作为过滤器的名称，那么参数是可选的。注册后，你"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"可以在模板中使用与 Jinja2 内置过滤器相同的过滤器，例如，如果您在上下文中有一个名为 "
```suggestion
"可以在模板中使用与 Jinja2 内置过滤器相同的过滤器，例如，如果你在上下文中有一个名为 "
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"为了将新变量自动注入到模板的上下文中，Flask 中存在上下文处理器。上下文处理器在呈现"
```suggestion
"Flask 中的上下文处理器可以将新变量自动注入到模板的上下文中。上下文处理器在渲染"
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"后，此字典的键和值将与应用程序中所有模板的模板上下文合并："
```suggestion
"模板之前运行，并且能够将新值注入到模板上下文中。上下文处理器是一个返回字典的函数。"
"此字典的键和值将与应用程序中所有模板的模板上下文合并："
```

2023-08-23 14:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"您也可以将 `format_price` 构建为模板过滤器（请参阅 :ref:`registering-filters`），但这演示了如何在上下文处理器中传递函数。"
```suggestion
"你也可以将 `format_price` 构建为模板过滤器（请参阅 :ref:`registering-filters`），但这演示了如何在上下文处理器中传递函数。"
```

2023-08-23 15:08 UTC, lrsgzs commented
谢谢你的修正，已经在重新commit了

2023-08-27 10:11 UTC, greyli requested changes

2023-08-27 10:11 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +msgstr "向下面这样导入上下文："
```suggestion
msgstr "像下面这样导入上下文："
```

2023-08-27 10:11 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/templating.po
> +"本中使用它们，你就必须用所谓的“实体”来代替它们。不这样做不仅会因为用户无法在文本中用这些"
```suggestion
"本中使用它们，你就必须用所谓的“实体”来代替它们。不这样做不仅会让用户因为无法在文本中用这些"
```

2023-10-11 14:25 UTC, greyli approved these changes

2023-10-11 14:25 UTC, merged

2023-10-11 14:26 UTC, greyli commented
Merged, thanks!