L takamori translate shell
greyli/flask-docs-zh pull request #42
Opened 2021-05-28 14:20 UTC by LTakamori

- fixes #<issue number>

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"`~flask.g` ， :data:`~flask.request` 等对象无法被使用。但假如你写的代码却依赖"
```suggestion
"不过依然存在一些便利的辅助工具，它们使得你使用 shell 的体验更加愉快。交互"
"式的控制台中的主要问题是你不能像浏览器一样触发一个请求，即无法使用说  :data:"
"`~flask.g` ， :data:`~flask.request` 等对象。但假如你写的代码依赖"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"于它们来进行调试，那么你应该怎么做呢？"
```suggestion
"它们来进行调试，那么你应该怎么做呢？"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"shell 的场景下，还能用于单元测试以及其他需要虚假请求的情况下。"
```suggestion
"shell 的场景下，还能用于单元测试以及其他需要伪造请求的情况。"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +msgstr "通常情况下，我建议你在继续之前先阅读  :doc:`reqcontext` 这一章节。"
```suggestion
msgstr "通常情况下建议先阅读  :doc:`reqcontext` 这一章节。"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +msgstr "发送请求前/后的动作"
```suggestion
msgstr "触发请求前/后的动作"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"导致当前用户没有被存储在 :data:`~flask.g` 中等一系列错误。"
```suggestion
"仅仅创建请求上下文还不够，你还没有执行请求前的一般会执行的动作。假如在请求前的"
"钩子中包含了连接数据库的操作，这会导致你的数据库仍不可用，这么做还有可能"
"导致当前用户没有被存储在 :data:`~flask.g` 中等一系列错误。"
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"如果要关闭一个请求，你需要在请求后函数（由 :meth:`~flask.Flask."
```suggestion
"如果要关闭一个请求，你需要在请求后钩子函数（由 :meth:`~flask.Flask."
```

2021-05-29 02:21 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"的地方。"
```suggestion
"执行。 所以，在这里释放之前由请求上下文申请的资源（比如数据库连接）"
"就相当合适了。"
```

2021-06-07 01:18 UTC, frostming approved these changes

2021-06-09 13:32 UTC, greyli requested changes

2021-06-09 13:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"式的控制台中的主要问题是你不能像浏览器一样触发一个请求，即无法使用说  :data:"
这里似乎多了一个「说」？「说」后面多了一个空格。

2021-06-09 13:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +msgstr "通常情况下建议先阅读  :doc:`reqcontext` 这一章节。"
ReST 符号前有多余空格，下面还有几处，不再一一指出。

2021-06-09 13:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"`~flask.g` ， :data:`~flask.request` 等对象。但假如你写的代码依赖"
标点和 ReST 符号之间不用加空格，后续有多处，不再一一指出。

2021-06-09 13:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +"执行。 所以，在这里释放之前由请求上下文申请的资源（比如数据库连接）"
「所以」前有多余空格。

2021-06-09 13:32 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/shell.po
> +msgstr "你只需将它们放入一个模块（举个例子 `shelltools` ）并将其导入即可："
「举个例子」改为「比如」是不是更好？

2021-06-12 08:12 UTC, greyli approved these changes

2021-06-12 08:17 UTC, merged