Translate docs/patterns/caching
greyli/flask-docs-zh pull request #69
Opened 2021-06-05 07:36 UTC by pk00749

- [x] 在 README.md 中勾选翻译的章节条目（把方括号里的空格替换为 `x`）.
- [x] 在本地生成文档并预览输出，处理所有错误和异常。
- [x] 运行 `pre-commit` 钩子，处理所有问题。
- [x] 更新 `.po` 文件顶部的 `Last-Translator` 字段。

2021-06-10 05:46 UTC, greyli requested changes

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Language: en_GB\n"
Language 字段的值需要是 zh_CN\n

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Plural-Forms: nplurals=2; plural=(n != 1);\n"
删除 Plural-Forms 字段

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"当你的应用运行缓慢，抛出里面的一些缓存。好吧，至少这是最简单的提速方法。"
throw ... in 应该被译为「扔……进去」。Well 可以不译。

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"究竟缓存是做什么？假设你有一个需要消耗一些时间来完成工作的函数，但在5分钟"
这两句需要优化。

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Flask itself does not provide caching for you, but `Flask-Caching <https://flask-caching.readthedocs.io/en/latest/>`_, an "
不需要改动原文的链接语法。

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Flask-Caching支持多种后后端，同时甚至可以开发你自己的缓存后端。"
多了一个「后」。

2021-06-10 05:46 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Flask自身对你不提供缓存，但`Flask-Caching <https://flask-caching.readthedocs.io/en/latest/>`，一个Flask的扩展可以做到。"
中英文之间需要添加空格，其他还有几处。ReST 语法和中文之间也要加空格。

2021-06-12 09:26 UTC, greyli commented
请在 6/16 前更新翻译。

2021-06-12 10:14 UTC, pk00749 commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"Flask itself does not provide caching for you, but `Flask-Caching <https://flask-caching.readthedocs.io/en/latest/>`_, an "
改动的原因是tests后出现如下的错误：
Warning, treated as error:
/home/runner/work/flask-docs-zh/flask-docs-zh/docs/patterns/caching.rst:11:inconsistent references in translated message. original: ['`Flask-Caching`_'], translated: []
ERROR: InvocationError for command /home/runner/work/flask-docs-zh/flask-docs-zh/.tox/docs/bin/sphinx-build -W -b html -d /home/runner/work/flask-docs-zh/flask-docs-zh/.tox/docs/tmp/doctrees docs /home/runner/work/flask-docs-zh/flask-docs-zh/.tox/docs/tmp/html (exited with code 2)

2021-06-12 10:19 UTC, pk00749 commented
> 请在 6/16 前更新翻译。

你好。不好意思，现在抓紧修改。

2021-06-12 10:55 UTC, greyli approved these changes

2021-06-12 15:02 UTC, frostming requested changes

2021-06-12 15:02 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
```suggestion
"如果你的应用运行缓慢，那就加一些缓存。至少这是最简单的加速方法。缓存有什么"
"作用？假设你有一个函数需要花费一些时间完成执行，但是希望计算结果在 5 分钟"
"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
```
原句不太通顺，修改了一下。

2021-06-13 00:45 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
「but the results would still be good enough if they were 5 minutes old」这里的意思并不是「希望计算结果在 5 分钟以后……」，而是指如果这些结果五分钟后仍然可以用（表明这个计算结果对时间不敏感），那就缓存这个结果。表明的是状态，而不是期望。

2021-06-15 12:40 UTC, frostming commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
这里的问题出在'So, then the idea is ...'，不能用「一个好主意是」，否则前面就需要设想一个问题

2021-06-16 00:42 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
@FesonX 这里怎么翻译比较好，有什么建议吗？

2021-06-19 00:57 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
@greyli 抱歉工作日回复较晚。这里用的“结果 5 分钟后可用”我同意你的想法，不是一种期望，而是预期的结果。
我的翻译是：[假设你有一个函数需要花费一些时间完成执行，它的运算结果即使在5分钟以后仍然可用。]
这里的 `but` 无需翻译

2021-06-19 01:51 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
没事。那最后一句呢？「So then the idea is that you actually put the result of that calculation into a cache for some time.」

2021-06-20 02:06 UTC, FesonX commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
@greyli 这里的 idea 用好主意确实不合适。部分同意 @frostming 。
idea 的英文释义是 `a thought or suggestion as to a possible course of action.` 用作建议、做法都是可以的
我的翻译是：[那么，有一种构想是将计算结果放入缓存一段时间。]

2021-06-25 14:12 UTC, greyli commented on docs/locales/zh_CN/LC_MESSAGES/patterns/caching.po
> +"以后仍然可以使用。那么，一个好主意是把这个计算结果保留在缓存里一段时间。"
直译太别扭了，我建议最后一句翻译成「那么，你就可以把这个计算结果保留在缓存里一段时间。」

2021-06-25 14:28 UTC, merged

2021-06-25 14:30 UTC, greyli commented
先合并了，后续有改进建议可以单独创建 PR 更新。

@pk00749 谢谢！

2021-06-25 14:31 UTC, pk00749 commented
不好意思。翻译质量不高。这回学习了很多。谢谢大佬。